config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/super-duper-fiesta:
      branch: main
      repo: https://github.com/PalomoIFCA/super-duper-fiesta
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.cadet_forgiving_hedgehog.sh
        container: qc.acc_persimmon_apathetic_kiwi
  QC.Doc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_gracious_raccoon.sh
        container: qc.doc_forest_ambitious_griffin
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_sad_eel.sh
        container: qc.doc_umber_diplomatic_viper
      github.com/PalomoIFCA/super-duper-fiesta markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.puce_analytical_salamander.sh
        container: qc.doc_grege_funny_pangolin
  QC.Lic:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta licensee:
        commands:
        - /usr/bin/env sh .sqa/script.umber_reserved_rattlesnake.sh
        container: qc.lic_silver_balanced_tarantula
  QC.Ver:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.currant_stoic_jackal.sh
        container: qc.ver_ash_generous_kiwi
timeout: 5400
