config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/super-duper-fiesta:
      branch: main
      repo: https://github.com/PalomoIFCA/super-duper-fiesta
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-indigo-fox.sh
        container: qc.acc_blurry-grey-dormouse
  QC.Doc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-lime-turtle.sh
        container: qc.doc_flaky-taupe-jellyfish
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-asparagus-tapir.sh
        container: qc.doc_wimpy-cinnabar-seal
      github.com/PalomoIFCA/super-duper-fiesta markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-charcoal-greyhound.sh
        container: qc.doc_baggy-mauve-skunk
  QC.Lic:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-razzmatazz-urchin.sh
        container: qc.lic_hasty-khaki-numbat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cardinal-boar.sh
        container: qc.ver_scaly-fuchsia-neanderthal
timeout: 5400
