config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/super-duper-fiesta:
      branch: main
      repo: https://github.com/PalomoIFCA/super-duper-fiesta
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-olive-lion.sh
        container: qc.acc_skinny-mustard-kangaroo
  QC.Doc:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-pear-mandrill.sh
        container: qc.doc_ready-lemon-birman
      github.com/PalomoIFCA/super-duper-fiesta git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-bronze-shrew.sh
        container: qc.doc_woolly-violet-quetzal
      github.com/PalomoIFCA/super-duper-fiesta markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-plum-shrew.sh
        container: qc.doc_gloppy-periwinkle-dane
  QC.Lic:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-burgundy-flamingo.sh
        container: qc.lic_cranky-magnolia-grouse
  QC.Ver:
    repos:
      github.com/PalomoIFCA/super-duper-fiesta get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-ivory-mouse.sh
        container: qc.ver_leaky-coral-frigatebird
timeout: 5400
