services:
  qc.acc_blurry-grey-dormouse:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_baggy-mauve-skunk:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_flaky-taupe-jellyfish:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_wimpy-cinnabar-seal:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_hasty-khaki-numbat:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_scaly-fuchsia-neanderthal:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
